export const PAY_PRODUCT="PAY_PRODUCT";
export const ADD_TO_CART="ADD_TO_CART";
export const ADD_TO_CART_SUCCESS="ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILED="ADD_TO_CART_FAILED";
export const ADD_TO_LOGIN="ADD_TO_LOGIN";
export const LOAD_CART="LOAD_CART";
export const LOAD_CART_SUCCESS="LOAD_CART_SUCCESS";
export const LOAD_CART_FAILED="LOAD_CART_FAILED";
